title: I'm Luander
description: > # this means to ignore newlines until "baseurl:"
  I love to hack systems and I also love to prevent them from being hacked.
  In real life I enjoy learning new stuff such as making the perfect espresso or sharpening knifes using a wetstone.
  I run my own Kubernetes cluster and I suck at it, for now.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luander.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Luander Ribeiro
author-img: luander-ribeiro.png
about-author: I'm a security engineer. Talk to me about pentesting, code assessments, Azure, Kubernetes, coffee, beer, Android, old rock and roll music, games, dogs and more
social-twitter: luanderock # add your Twitter handle
social-github: luander # add your Github handle
social-linkedin: luander # add your Linkedin handle
social-email: iam@luander.net # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
