# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  serviceconnection: $(serviceconnection)
  subscriptionId: $(subscriptionId)

stages:
- stage: build
  jobs:
  - job: build
    steps: 
    - task: Docker@0.209.0
      displayName: 'Run Jekyll'
      inputs:
        containerRegistryType: 'Container Registry'
        action: 'Run an image'
        # use the latest version of jekyll/builder docker image from Docker Hub
        imageName: 'jekyll/builder:latest'
        # mount the source code directory and binaries directory in the container
        volumes: |
          $(build.sourcesDirectory)/site:/srv/jekyll
          $(build.binariesDirectory)/site:/srv/jekyll/_site
        # set an environment variable inside the container
        envVars: 'JEKYLL_ENV=production'
        # execute a custom script when the container starts
        containerCommand: '/srv/jekyll/tools/azuredevopsbuild.sh -d /srv/jekyll/_site'
        # do not run the container in background
        detached: false
    # publish the artifact to Azure DevOps
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(build.binariesDirectory)/site'
        artifactName: site

- stage: deploy
  dependsOn: build
  jobs:
  - job: deploy
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'site'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceconnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'personal-website'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'templates/storage.json'
        deploymentMode: 'Incremental'